USE [master]
GO
/****** Object:  Database [ACADEMICO_EXPORT]    Script Date: 15/06/2023 3:30:41 ******/
CREATE DATABASE [ACADEMICO_EXPORT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ACADEMICO_EXPORT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ACADEMICO_EXPORT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ACADEMICO_EXPORT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ACADEMICO_EXPORT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ACADEMICO_EXPORT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET ARITHABORT OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET RECOVERY FULL 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET  MULTI_USER 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ACADEMICO_EXPORT', N'ON'
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET QUERY_STORE = ON
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ACADEMICO_EXPORT]
GO
/****** Object:  Table [dbo].[Docente]    Script Date: 15/06/2023 3:30:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Docente](
	[ID] [int] NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Apellido] [varchar](50) NULL,
	[Especialidad] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ACADEMICO_EXPORT] SET  READ_WRITE 
GO
